<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>$(SolutionName).$(MSBuildProjectName)</AssemblyName>
	<RootNameSpace>$(SolutionName).$(MSBuildProjectName.Replace(" ", "_"))</RootNameSpace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aids\Aids.csproj" />
  </ItemGroup>

</Project>
